### ISSUE TITLE
error while applying snapshot with dockerized pathfinder image

### ISSUE THREAD

**Issue by NoFeeding** [eqlabs/pathfinder#1837]
hi everyone, recently I got task to run Pathfinder mainnet for services within my office.
While I set everything up , the sync is super slow so I decided to make use of snapshot to get latest height.
However every time I download snapshot and decompressed it in the mounted data directory. Docker container cannot start properly. Below is the docker log with RUST_BACKTRACE set to full. 
Please advice proper steps that I should follow to make use of the snapshot for faster height sync or any other snapshot files I should choose. Thanks in advance!

```
2024-03-04T10:44:22  INFO 🏁 Starting node. version="v0.11.1"
thread 'main' panicked at crates/pathfinder/src/bin/pathfinder/main.rs:115:6:
called `Result::unwrap()` on an `Err` value: Setting journal mode to rollback

Caused by:
    0: disk I/O error
    1: Error code 3850: I/O error in the advisory file locking layer

Stack backtrace:
   0: pathfinder::async_main::{{closure}}
   1: pathfinder::main
   2: std::sys_common::backtrace::__rust_begin_short_backtrace
   3: main
   4: <unknown>
   5: __libc_start_main
   6: _start
stack backtrace:
   0:     0x55891ff395cf - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55891ff395cf - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55891ff395cf - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55891ff395cf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55891f77bccc - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55891f77bccc - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55891ff0783d - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55891ff3abee - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55891ff3abee - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55891ff3a7b4 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55891ff3b7bb - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55891ff3b7bb - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55891ff3b2cc - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55891ff3b226 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55891ff3b211 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55891eecedd4 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55891eecf342 - core::result::unwrap_failed::h8c4b86241881fbbb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
  17:     0x55891f052432 - pathfinder::async_main::{{closure}}::h136e3a7394222f49
  18:     0x55891f037474 - pathfinder::main::h8517c94119a3bb8b
  19:     0x55891efa1313 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9d232beb0410b1c9
  20:     0x55891f06b167 - main
  21:     0x7ff0e087924a - <unknown>
  22:     0x7ff0e0879305 - __libc_start_main
  23:     0x55891ef1c9b1 - _start
  24:                0x0 - <unknown>``
```

**Comment by kkovaacs** [comment]
What kind of setup (OS, file system for the data directory) are you using? This looks like an issue with the underlying file system.

**Comment by tarrencev** [comment]
@kkovaacs I'm running into the same issue when running inside a k8s cluster using the provided pathfinder image and snapshot

The configuration looks like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pathfinder
  name: pathfinder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pathfinder
  template:
    metadata:
      labels:
        app: pathfinder
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: download-decompress-db
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache rclone zstd curl
              mkdir -p /root/.config/rclone
              echo "[pathfinder-snapshots]
              type = s3
              provider = Cloudflare
              env_auth = false
              access_key_id = 7635ce5752c94f802d97a28186e0c96d
              secret_access_key = 529f8db483aae4df4e2a781b9db0c8a3a7c75c82ff70787ba2620310791c7821
              endpoint = https://cbf011119e7864a873158d83f3304e27.r2.cloudflarestorage.com
              acl = private" > /root/.config/rclone/rclone.conf
              if [ ! -f /usr/share/pathfinder/data/mainnet.sqlite ]; then
                rm -rf /usr/share/pathfinder/data
                rclone copy -P pathfinder-snapshots:pathfinder-snapshots/mainnet_0.11.0_595424.sqlite.zst /usr/share/pathfinder/data
                zstd -T0 -d /usr/share/pathfinder/data/mainnet_0.11.0_595424.sqlite.zst -o /usr/share/pathfinder/data/mainnet.sqlite
                rm /usr/share/pathfinder/data/mainnet_0.11.0_595424.sqlite.zst
              fi
          volumeMounts:
            - name: pathfinder-data
              mountPath: /usr/share/pathfinder/data
      containers:
        - name: pathfinder
          image: eqlabs/pathfinder:v0.11.2
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: PATHFINDER_ETHEREUM_API_URL
              value: https://eth-mainnet.g.alchemy.com/v2/QeaeS11yKvkekVWGYLwgVqLeRu3xK7z8
            - name: PATHFINDER_WEBSOCKET_ENABLED
              value: "true"
            - name: PATHFINDER_RPC_CORS_DOMAINS
              value: "*"
            - name: PATHFINDER_DATA_DIRECTORY
              value: /usr/share/pathfinder/data
          ports:
            - containerPort: 9545
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ssl
              name: ssl
            - name: pathfinder-data
              mountPath: /usr/share/pathfinder/data
          resources:
            requests:
              memory: 16Gi
              cpu: "4"
      serviceAccountName: default
      nodeSelector:
        topology.kubernetes.io/zone: "us-east4-a"
      volumes:
        - hostPath:
            path: /etc/ssl
          name: ssl
        - name: pathfinder-data
          persistentVolumeClaim:
            claimName: pathfinder-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-data
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
```

**Comment by tarrencev** [comment]
@kkovaacs I'm running into the same issue when running inside a k8s cluster using the provided pathfinder image and snapshot

The configuration looks like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pathfinder
  name: pathfinder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pathfinder
  template:
    metadata:
      labels:
        app: pathfinder
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: download-decompress-db
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache rclone zstd curl
              mkdir -p /root/.config/rclone
              echo "[pathfinder-snapshots]
              type = s3
              provider = Cloudflare
              env_auth = false
              access_key_id = 7635ce5752c94f802d97a28186e0c96d
              secret_access_key = 529f8db483aae4df4e2a781b9db0c8a3a7c75c82ff70787ba2620310791c7821
              endpoint = https://cbf011119e7864a873158d83f3304e27.r2.cloudflarestorage.com
              acl = private" > /root/.config/rclone/rclone.conf
              if [ ! -f /usr/share/pathfinder/data/mainnet.sqlite ]; then
                rm -rf /usr/share/pathfinder/data
                rclone copy -P pathfinder-snapshots:pathfinder-snapshots/mainnet_0.11.0_595424.sqlite.zst /usr/share/pathfinder/data
                zstd -T0 -d /usr/share/pathfinder/data/mainnet_0.11.0_595424.sqlite.zst -o /usr/share/pathfinder/data/mainnet.sqlite
                rm /usr/share/pathfinder/data/mainnet_0.11.0_595424.sqlite.zst
              fi
          volumeMounts:
            - name: pathfinder-data
              mountPath: /usr/share/pathfinder/data
      containers:
        - name: pathfinder
          image: eqlabs/pathfinder:v0.11.2
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: info
            - name: PATHFINDER_ETHEREUM_API_URL
              value: https://eth-mainnet.g.alchemy.com/v2/...
            - name: PATHFINDER_WEBSOCKET_ENABLED
              value: "true"
            - name: PATHFINDER_RPC_CORS_DOMAINS
              value: "*"
            - name: PATHFINDER_DATA_DIRECTORY
              value: /usr/share/pathfinder/data
          ports:
            - containerPort: 9545
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ssl
              name: ssl
            - name: pathfinder-data
              mountPath: /usr/share/pathfinder/data
          resources:
            requests:
              memory: 16Gi
              cpu: "4"
      serviceAccountName: default
      nodeSelector:
        topology.kubernetes.io/zone: "us-east4-a"
      volumes:
        - hostPath:
            path: /etc/ssl
          name: ssl
        - name: pathfinder-data
          persistentVolumeClaim:
            claimName: pathfinder-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-data
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
```
